name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install gocv
      run: |
        git clone https://github.com/hybridgroup/gocv.git
        cd gocv
        make install
        cd ..
        echo "Successfully installed gocv!"

    - name: Build
      run: make build

    - name: Test
      run: make test-short
